### PR TITLE
fix: only use 1st cfg file when logging in, dont add all ctxts (#966)

### LINKED ISSUE #966: Using $KUBECONFIG with several files, logging into the cluster dumps all contexts into the default config files
**Steps:**
1. ASSERT: have several config files, all of them listed on the KUBECONFIG env var
* `$KUBECONFIG`
```bash
export KUBECONFIG=${HOME}/.kube/config:${HOME}/.kube/minikube.yaml:${HOME}/.kube/sandbox.yaml
```
* config
```yaml
apiVersion: v1
current-context: rh-sandbox
kind: Config
preferences: {}
```
* minikube.yaml
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /Users/adietish/.minikube/ca.crt
    extensions:
    - extension:
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: cluster_info
    server: https://127.0.0.1:41825
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 08 Jan 2025 15:05:54 CET
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: kube-node-lease
    user: minikube
  name: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /Users/adietish/.minikube/profiles/minikube/client.crt
    client-key: /Users/adietish/.minikube/profiles/minikube/client.key
```
* sandbox.yaml
```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://api.XXXX.openshiftapps.com:6443
  name: rh-sandbox
contexts:
- context:
    cluster: rh-sandbox
    namespace: adietish-dev
    user: adietish/rh-sandbox
  name: rh-sandbox
current-context: ""
kind: Config
preferences: {}
users:
- name: adietish/rh-sandbox
  user:
    token: sha256~XXXXXXXXXXXXXXXXXXXEMhxfNi614txI
```
2. EXEC: pick ctx menu action "Log in to Cluster"
3. ASSERT: Login dialog is show
4. EXEC: get the token and paste into the Login dialog into the field "Token:"
5. EXEC: hit "OK"
6. ASSERT: The plugin is logged into the RH sandbox
7. EXEC: cat `~/.kube/config`

**Result:**
`~/.kube/config` was altered. All the above contexts were dumped into it: Additionally a new context was added for the cluster, that was listed in the dialog.

```
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://api.rm1.0a51.p1.openshiftapps.com:6443
  name: api-rm1-0a51-p1-openshiftapps-com:6443
contexts:
- context:
    cluster: apiXXXXopenshiftapps-com:6443
    namespace: adietish-dev
    user: adietish/apiXXXXXopenshiftapps-com:6443
  name: adietish-dev/apiXXXXXopenshiftapps-com:6443/adietish
- context:
    cluster: minikube
    extensions:
    - extension:
        provider: minikube.sigs.k8s.io
        version: v1.34.0
      name: context_info
    namespace: kube-node-lease
    user: minikube
  name: minikube
- context:
    cluster: rh-sandbox
    namespace: adietish-dev
    user: adietish/rh-sandbox
  name: rh-sandbox
current-context: adietish-dev/api-rm1-0a51-p1-openshiftapps-com:6443/adietish
kind: Config
preferences: {}
users:
- name: adietish/apiXXXXXopenshiftapps-com:6443
  user:
    token: sha256XXXXXXXXXEMhxfNi614txI
```

### PR DESCRIPTION
**Pull request by adietish**
depends on https://github.com/redhat-developer/intellij-common/pull/264
fixes #966

### CODE REVIEW

File: gradle.properties [hunk 1]
```diff
@@ -11,7 +11,7 @@ gradleVersion=8.5
 
 # Plugin Dependencies -> https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html
 platformBundledPlugins=com.intellij.java, org.jetbrains.plugins.yaml, org.jetbrains.plugins.terminal
-platformPlugins=com.redhat.devtools.intellij.telemetry:1.2.1.62, com.redhat.devtools.intellij.kubernetes:1.4.0.4
+platformPlugins=com.redhat.devtools.intellij.telemetry:1.2.1.62
```
Comment (adietish) [inline gradle.properties:14]: there's no dependency of openshift to kubernetes. The only thing that we may want is that people would install kubernetes plugin when installing the openshift plugin. We need to remove the kubernetes plugin 1.4 though for things to compile. Kubernetes 1.4 is using kubernetes-client 6.x and overrides the direct dependency onto 7.x causing compilation to fail.

File: src/main/java/org/jboss/tools/intellij/openshift/utils/oc/OcCli.java [hunk 2]
```diff
@@ -60,10 +63,30 @@ private static void execute(@NotNull File workingDirectory, String command, Map<
 
   @Override
   public void login(String url, String userName, char[] password, char[] token) throws IOException {
+    var args = new ArrayList<String>();
+    args.add("login");
+    args.add(url);
+    args.add("--insecure-skip-tls-verify");
+    addKubeconfigParameter(args);
```
Comment (adietish) [inline src/main/java/org/jboss/tools/intellij/openshift/utils/oc/OcCli.java:70]: this is the main change here. Use `--kubeconfig` so that the contexts that are defined in the other configs files are not dumped into the first one. Only a new context for the cluster (that we're logging in) is added.

**Comment by adietish** [comment]
/override "Integration UI Tests with Local Kind Cluster Context Report" "ci/prow/e2e-openshift"

**Comment by adietish** [comment]
/override "Integration UI Tests with Local Kind Cluster Context Report"

**Review by sbouchet — APPROVED** [review]
LGTM.

**Comment by adietish** [comment]
/override "Integration UI Tests with Local Kind Cluster Context Report"

**Comment by adietish** [comment]
/override "Integration UI Tests with Local Kind Cluster Context Report"
