### PR TITLE
Adding more log and fix cluster view 

### LINKED ISSUE #147: Cannot login to cluster when user home is mounted as network drive
[kind/bug]

## What versions of software are you using?
- Operating System: Windows
- IntelliJ version: 2019.3
- OpenShift version: odo 1.0.2

## Actual behavior
This is a issue created to follow the discussion on gitter for a user that cannot log in the cluster using a network drive as home folder.
The openshift view list the cluster but not the projects.
the cluster tree is empty

using odo in commandline ( odo login ) works.

user screenshot : https://files.gitter.im/redhat-developer/openshift-connector/Yuel/image.png

## Expected behavior
user can be able to login to the cluster.

## Any logs, error output, etc?
There is no output/error neither in the UI or the logs.

### PR DESCRIPTION
**Pull request by sbouchet**
## What is the purpose of this change? What does it change?
first improvement for fixing issue.

## Was the change discussed in an issue?
fixes #147 

## How to test changes?
try with a windows home folder located in a network drive.

### CODE REVIEW

**Comment by sbouchet** [comment]
draft PR to be merged when #89 will be merged.

File: src/main/java/org/jboss/tools/intellij/openshift/Constants.java [hunk 1]
```diff
@@ -32,4 +32,6 @@
     public static final String OCP4_CONFIG_NAMESPACE = "openshift-config-managed";
     public static final String OCP4_CONSOLE_PUBLIC_CONFIG_MAP_NAME = "console-public";
     public static final String OCP4_CONSOLE_URL_KEY_NAME = "consoleURL";
+
+    public static final String LOGGER_CATEGORY = "org.jboss.tools.intellij.openshift";
```
Comment (jeffmaury) [inline src/main/java/org/jboss/tools/intellij/openshift/Constants.java]: Not needed

File: src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/SetCurrentClusterAction.java [hunk 2]
```diff
@@ -11,7 +11,9 @@
 package org.jboss.tools.intellij.openshift.actions.cluster;
 
 import com.intellij.openapi.actionSystem.AnActionEvent;
+import com.intellij.openapi.diagnostic.Logger;
```
Comment (jeffmaury) [inline src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/SetCurrentClusterAction.java]: Use raw SLF4J API to be consistent and more standard

File: src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigHelper.java [hunk 3]
```diff
@@ -42,40 +43,18 @@ public static Config safeLoadKubeConfig() {
...
         File f = new File(getKubeConfigPath());
-        if (f.exists()) {
+        if (Files.exists(f.toPath())) {
             return KubeConfigUtils.parseConfig(f);
         } else {
             return new ConfigBuilder().build();
         }
     }
 
-    public static boolean isKubeConfigParsable() {
```
Comment (jeffmaury) [inline src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigHelper.java]: What's the rationale for this removal. Is this because this method is not used ?

File: src/main/java/org/jboss/tools/intellij/openshift/Constants.java (hunk 1 above)
Comment (sbouchet) [reply src/main/java/org/jboss/tools/intellij/openshift/Constants.java]: removed.

File: src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/SetCurrentClusterAction.java (hunk 2 above)
Comment (sbouchet) [reply src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/SetCurrentClusterAction.java]: done.

File: src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigHelper.java (hunk 3 above)
Comment (sbouchet) [reply src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigHelper.java]: yes, while on working on that class, i noticed these methods are not used, so i removed it.

**Comment by sbouchet** [comment]
testPR
