### PR TITLE
fix: made sure telemetry sender is initialized (#926)

### LINKED ISSUE #926: Uninstall helm chart & remove helm repo error with "this.telemetrySender is null"
**Steps:**
1. ASSERT: have a helm chart installed that you can uninstall
2. EXEC: pick "Uninstall" in the ctx menu of the helm chart in the tree

**Result:**
Helm chart is uninstalled but an error dialog shows up, reporting an error with telemetry:

```java
java.lang.NullPointerException: Cannot invoke "org.jboss.tools.intellij.openshift.telemetry.TelemetrySender.sendTelemetryResults(org.jboss.tools.intellij.openshift.telemetry.TelemetryService$TelemetryResult)" because "this.telemetrySender" is null
	at org.jboss.tools.intellij.openshift.actions.TelemetryAction.sendTelemetryResults(TelemetryAction.java:38)
	at org.jboss.tools.intellij.openshift.actions.helm.UninstallReleaseAction.lambda$actionPerformed$2(UninstallReleaseAction.java:68)
	at org.jboss.tools.intellij.openshift.actions.ActionUtils$1.run(ActionUtils.java:74)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:221)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:46)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:220)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run$$$capture(ProgressRunner.java:500)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext$runAsCoroutine$1.invoke(propagation.kt:81)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:86)
	at com.intellij.util.concurrency.ChildContext.runAsCoroutine(propagation.kt:81)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:466)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

The same happens when you remove a helm repo:

**Steps:**
1. EXEC: list the helm repos, pick "Remove Repositories"
2. EXEC: Confirm removal in the upcoming dialog

**Result:**
Error dialog shows up, reporting an error with telemetry.

### PR DESCRIPTION
**Pull request by adietish**
fixes #926

### CODE REVIEW

File: src/main/java/org/jboss/tools/intellij/openshift/actions/HelmAction.java [hunk 1]
```diff
@@ -29,14 +30,28 @@ protected HelmAction(Class... filters) {
     super(filters);
   }
 
-  @Override
```
Comment (sbouchet) [inline src/main/java/org/jboss/tools/intellij/openshift/actions/HelmAction.java:32]: this is still a valid Override from parent hierarchy

**Review by sbouchet — APPROVED** [review]
LGTM. no more errors displayed
