### PR TITLE
fix: show 'no url/binding' node, use async leafstate for component (#687)

### LINKED ISSUE #687: URL aren't displayed anymore when component is on dev mode
[kind/bug]

## What versions of software are you using?
- Operating System: Fedora
- IntelliJ version: 2023.3
- OpenShift version: 

## What did you run exactly?
When running component in dev mode, URLS are'nt displayed anymore as child of the component.

## Actual behavior
current main 

Capture d’écran du 2024-02-01 11-25-54

## Expected behavior
from 1.6.0

Capture d’écran du 2024-02-01 11-21-01

### PR DESCRIPTION
**Pull request by adietish**
fixes #687

### CODE REVIEW

File: src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java [hunk 1]
```diff
@@ -94,9 +94,7 @@ public Object getApplicationsRoot() {
 
     @Override
     public @NotNull LeafState getLeafState(@NotNull Object element) {
-        if (element instanceof ComponentNode) {
-            return LeafState.ALWAYS;
```
Comment (adietish) [inline src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java:98]: this is the fix: the leafstate for `ComponentNode` is now async

File: src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java [hunk 2]
```diff
@@ -221,34 +219,47 @@ private List<BaseNode<?>> load(Callable<List<BaseNode<?>>> callable, NamespaceNo
...
+                componentNode.getParent().getName(),
+                componentNode.getComponent().getPath(),
+                componentNode.getName())
+              .stream()
+              .map(url -> new URLNode(componentNode, url))
+              .collect(Collectors.toList());
+            if (!urls.isEmpty()) {
+                nodes.addAll(urls);
+            } else {
+                nodes.add(new MessageNode<>(root, componentNode, "<No URLS>"));
```
Comment (adietish) [inline src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java:236]: @sbouchet: suggested enhancement: add a node "no URLs" if no urls were found for the component

File: src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java [hunk 3]
```diff
@@ -221,34 +219,47 @@ private List<BaseNode<?>> load(Callable<List<BaseNode<?>>> callable, NamespaceNo
...
+                componentNode.getParent().getName(),
+                componentNode.getComponent().getPath(),
+                componentNode.getName())
+              .stream()
+              .map(binding -> new BindingNode(componentNode, binding))
+              .collect(Collectors.toList());
+            if (!bindings.isEmpty()) {
+                nodes.addAll(bindings);
+            } else {
+                nodes.add(new MessageNode<>(root, componentNode, "<No Bindings>"));
```
Comment (adietish) [inline src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java:257]: @sbouchet: suggested enhancement: add a child "no bindings" if no urls were found for the component

File: src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java [hunk 4]
```diff
@@ -318,6 +329,11 @@ public Object getParentElement(@NotNull Object element) {
     public void commit() {
     }
 
+    @Override
+    public boolean isToBuildChildrenInBackground(@NotNull Object element) {
+        return true;
```
Comment (adietish) [inline src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsTreeStructure.java:334]: enhancement: retrieve children in a background thread (instead of UI thread)

**Comment by sbouchet** [comment]
@adietish : your enhancement are good idea, but may need more than 'just' displaying no url/url.
letme explain. 
URL are actually shown only when running on dev mode, because they are 'active' and the context action opens a webbrowser to that address.
If your idea is to show 'no URL', it shouldbe clear taht it's no ACTIVE url that can be browsed, because when you describe the component using odo, it always shows URL taht are listed on the devfile.
What i propose is to display more information.
- NO URL only when there is no URL in the devfile
- URL in grey state, when there is URL in the devfile but the compoent is not running
- URL in White/Green state, when the URL is active

this is somehow similar to what odo does, and we can rely on it to parse the state ( try out with descibe commands) .

WDYT ?

**Comment by sbouchet** [comment]
thanks for filling a new enhancement request.

**Review by sbouchet — APPROVED** [review]
LGTM. please follow up with #707
