### PR TITLE
#152: Added service catalog availability

### LINKED ISSUE #152: Add service catalog availability
[kind/Enhancement]
## Which functionality do you think we should update/improve?

We should detect if Service Catalog is available on the cluster before certains operations (create component, create service) instead of throwing an error.
This can be done by adding on new Odo method isServiceCatalogAvailable(client) and trying to cast the OpenShiftClient to the ServiceCatalogClient and catching the exception.

## Why is this needed? 

For better user interaction

### PR DESCRIPTION
**Pull request by sbouchet**
## What is the purpose of this change? What does it change?
Services are not always available on clusters. This feature adds some checks on the action to hide/show services related actions. 

## Was the change discussed in an issue?
fixes #152 

## How to test changes?
Unit tests updated to take in account the service availability on clusters.
Manual test can be performed in two clusters ( one with services, one without )

### CODE REVIEW

**Comment by sbouchet** [comment]
draft because it may cause merge conflicts with #162

File: src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java [hunk 1]
```diff
@@ -618,6 +622,20 @@ public void debug(String project, String application, String context, String com
     ExecHelper.executeWithTerminal(new File(component), false, command, "debug", "port-forward", "--local-port", port.toString());
   }
 
+  @Override
+  public boolean isServiceCatalogAvailable(OpenShiftClient client){
+    try {
+      ServiceCatalogClient sc = client.adapt(ServiceCatalogClient.class);
```
Comment (jeffmaury) [inline src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java]: Don't need to perform a request to check for service availability (which is bad as you call this method in Action.isVisible that will slow down the UI significantly). The Kubernetes/OpenShiftClient has a isAdaptableMethod(Class) that does the trick

Comment (sbouchet) [reply src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java]: done.
