### PR TITLE
fix: bump kubernetes-client to 7.0.0 (#921)

### LINKED ISSUE #921: Bump kubernetes-client 7.0.0
related to 
* https://github.com/redhat-developer/intellij-kubernetes/issues/794, 
* https://github.com/redhat-developer/intellij-knative/issues/257
* https://github.com/redhat-developer/intellij-common/issues/247

Support for multiple kubernetes config files will be available in kubernetes-client 7.0 (see https://github.com/fabric8io/kubernetes-client/issues/6240, https://github.com/redhat-developer/intellij-kubernetes/issues/779). We'll have to bump the kubernetes-client 7.0 in all our plugins/libraries.

### PR DESCRIPTION
**Pull request by adietish**
depends on merging https://github.com/redhat-developer/intellij-common/issues/247 and publishing intellij-common afterwards
fixes #921

### CODE REVIEW

**Comment by adietish** [comment]
Some maven artifacts seem not available in the maven repo yet. The build works fine locally (with locally built kubernetes-client artifacts) though.

**Comment by adietish** [comment]
kubernetes-client 7.0 was released: https://repo1.maven.org/maven2/io/fabric8/kubernetes-client/7.0.0/

**Comment by adietish** [comment]
Quite some changes required to be able to do the bump:
* config watcher has to hand over the new (merged) config, not the config file that changed
  ```java
      public interface Listener {
        void onUpdate(Config updatedConfig);
    }
  ```
  This then requires `ApplicationsRootNode` to hold a client instance that it is replacing if a meaningful change of a config file occurred. It then has to recreate odo and oc binaries with the new client.
* checking if a cluster is an OpenShift cluster now relies on `client.hasApiGroup("openshift.io", false);`. There's no `client#isSupported` any more.
* all tests have to be realigned with the lifecycle changes.
* etc.

File: src/main/java/org/jboss/tools/intellij/openshift/actions/project/ChangeActiveProjectAction.java [hunk 1]
```diff
@@ -189,4 +190,9 @@ public void run() {
       );
     }
   }
+
+  @Override
+  public @NotNull ActionUpdateThread getActionUpdateThread() {
```
Comment (adietish) [inline src/main/java/org/jboss/tools/intellij/openshift/actions/project/ChangeActiveProjectAction.java:195]: This could/should have arguably been fixed in a separate issue. When the cluster isn't reachable, the EDT is stuck waiting and the platform throws an exception indicating this fix.

**Comment by adietish** [comment]
@sbouchet please review, thanks.

**Comment by adietish** [comment]
With the change in [intellij-common](https://github.com/redhat-developer/intellij-common/pull/260) I need to update this PR to use the changed API

**Comment by adietish** [comment]
@sbouchet bumped to use intellij-common 1.9.7 (Final). Please review.

File: src/main/java/org/jboss/tools/intellij/openshift/actions/project/ChangeActiveProjectAction.java (hunk 1 above)
Comment (sbouchet) [reply src/main/java/org/jboss/tools/intellij/openshift/actions/project/ChangeActiveProjectAction.java:195]: nice catch !

**Comment by sbouchet** [comment]
@adietish hile testing using a fresh instance ( means NO context ) and trying to connect to  devsandbox, i get this error as soon i click on the login dialog: 
`Error: Process exited with an error: 1 (Exit value: 1) Error: unknown command "login" for "helm"  Did you mean this? plugin  Run 'helm --help' for usage.`

i don't see any Helm node on the tree either...

also, while looking a the logs, i get these one too:

```
java.lang.Throwable: org.jboss.tools.intellij.openshift.oauth.AccountService <clinit> requests org.jboss.tools.intellij.openshift.oauth.ui.DefaultLoginProvider instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.serviceContainer.ComponentManagerImplKt.checkOutsideClassInitializer(ComponentManagerImpl.kt:1586)
	at com.intellij.serviceContainer.ComponentManagerImplKt.getOrCreateInstanceBlocking(ComponentManagerImpl.kt:1555)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:751)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:695)
	at org.jboss.tools.intellij.openshift.oauth.LoginProvider.get(LoginProvider.java:25)
	at org.jboss.tools.intellij.openshift.oauth.AccountService.<init>(AccountService.java:31)
	at org.jboss.tools.intellij.openshift.oauth.AccountService.<clinit>(AccountService.java:29)
	at org.jboss.tools.intellij.openshift.oauth.DefaultTokenProvider.getToken(DefaultTokenProvider.java:24)
	at org.jboss.tools.intellij.openshift.ui.sandbox.SandboxWorkflowPage.ssoLogin(SandboxWorkflowPage.java:107)
	at org.jboss.tools.intellij.openshift.ui.sandbox.SandboxWorkflowPage.retrieveState(SandboxWorkflowPage.java:122)
	at org.jboss.tools.intellij.openshift.ui.sandbox.SandboxWorkflowPage$4.run(SandboxWorkflowPage.java:192)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:491)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$7(CoreProgressManager.java:542)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:249)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:223)
	at com.intellij.platform.diagnostic.telemetry.helpers.TraceKt.use(trace.kt:45)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:222)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$14(CoreProgressManager.java:674)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:749)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:673)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:203)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:98)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:249)
	at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:502)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$18(ProgressRunner.java:467)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext$runInChildContext$1.invoke(propagation.kt:101)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:107)
	at com.intellij.util.concurrency.ChildContext.runInChildContext(propagation.kt:101)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$launchTask$19(ProgressRunner.java:463)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:735)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:732)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:732)
	at java.base/java.lang.Thread.run(Thread.java:1583)

```

**Comment by sbouchet** [comment]
follow up:
when using local kind, i can get the helm charts node.
but when i'm trying to create a new component, i noticed the logs gets populated with: 
```
com.intellij.diagnostic.PluginException: Empty menu item text for DeployComponentAction@MainMenu (org.jboss.tools.intellij.openshift.actions.component.DeployComponentAction). The default action text must be specified in plugin.xml or its class constructor [Plugin: org.jboss.tools.intellij.openshift]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.openapi.actionSystem.impl.Utils.reportEmptyTextMenuItem(Utils.kt:669)
	at com.intellij.openapi.actionSystem.impl.Utils.filterInvisible(Utils.kt:634)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenuInner(Utils.kt:543)
	at com.intellij.openapi.actionSystem.impl.Utils.fillMenu$intellij_platform_ide_impl(Utils.kt:476)
	at com.intellij.openapi.actionSystem.impl.Utils.fillPopupMenu(Utils.kt:435)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.updateChildren(ActionPopupMenuImpl.java:170)
	at com.intellij.openapi.actionSystem.impl.ActionPopupMenuImpl$MyMenu.show(ActionPopupMenuImpl.java:126)
	at com.intellij.ui.PopupHandler$2.invokePopup(PopupHandler.java:132)
	at com.intellij.ui.PopupHandler.mousePressed(PopupHandler.java:47)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6659)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3394)
	at com.intellij.ui.treeStructure.Tree.processMouseEvent(Tree.java:479)
	at java.desktop/java.awt.Component.processEvent(Component.java:6427)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5032)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4574)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4860)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:675)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:621)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$21(IdeEventQueue.kt:564)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:564)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16$lambda$15(IdeEventQueue.kt:355)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:857)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18$lambda$17$lambda$16(IdeEventQueue.kt:354)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2$lambda$1(IdeEventQueue.kt:1045)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.runWriteIntentReadAction(AnyThreadWriteThreadingSupport.kt:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:916)
	at com.intellij.openapi.application.WriteIntentReadAction.compute(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$2(IdeEventQueue.kt:1045)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:1054)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:117)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1054)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$18(IdeEventQueue.kt:349)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:395)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```
also, the dev on podman action isn't enabled ( it should be )

**Comment by sbouchet** [comment]
and last one ( maybe can be fixed in another issue ) :
```
2025-01-23 12:54:18,187 [3051803] SEVERE - #c.i.u.SlowOperations - Non-cancelable slow operations are prohibited inside read action. See SlowOperations.assertNonCancelableSlowOperationsAreAllowed javadoc.
java.lang.Throwable: Non-cancelable slow operations are prohibited inside read action. See SlowOperations.assertNonCancelableSlowOperationsAreAllowed javadoc.
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
	at com.intellij.util.SlowOperations.assertNonCancelableSlowOperationsAreAllowed(SlowOperations.java:128)
	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.set(PasswordSafeImpl.kt:107)
	at org.jboss.tools.intellij.openshift.oauth.model.ServersRepository.account2Node(ServersRepository.java:54)
	at org.jboss.tools.intellij.openshift.oauth.model.ServersRepository.server2Node(ServersRepository.java:65)
	at org.jboss.tools.intellij.openshift.oauth.model.ServersRepository.getState(ServersRepository.java:74)
	at org.jboss.tools.intellij.openshift.oauth.model.ServersRepository.getState(ServersRepository.java:28)
	at com.intellij.configurationStore.ComponentStoreImplKt.getStateForComponent$lambda$3(ComponentStoreImpl.kt:827)
	at com.intellij.openapi.application.rw.InternalReadAction.insideReadAction(InternalReadAction.kt:114)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable$lambda$4(InternalReadAction.kt:104)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2$lambda$1(cancellableReadAction.kt:32)
	at com.intellij.openapi.application.impl.AnyThreadWriteThreadingSupport.tryRunReadAction(AnyThreadWriteThreadingSupport.kt:351)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:971)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal$lambda$3$lambda$2(cancellableReadAction.kt:30)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:66)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:157)
	at com.intellij.openapi.application.rw.CancellableReadActionKt.cancellableReadActionInternal(cancellableReadAction.kt:28)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadCancellable(InternalReadAction.kt:103)
	at com.intellij.openapi.application.rw.InternalReadAction.tryReadAction(InternalReadAction.kt:87)
	at com.intellij.openapi.application.rw.InternalReadAction.readLoop(InternalReadAction.kt:74)
	at com.intellij.openapi.application.rw.InternalReadAction.access$readLoop(InternalReadAction.kt:16)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invokeSuspend(InternalReadAction.kt:53)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at com.intellij.openapi.application.rw.InternalReadAction$runReadAction$6.invoke(InternalReadAction.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:62)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:163)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.application.rw.InternalReadAction.runReadAction(InternalReadAction.kt:49)
	at com.intellij.openapi.application.rw.PlatformReadWriteActionSupport.executeReadAction(PlatformReadWriteActionSupport.kt:38)
	at com.intellij.openapi.application.ReadWriteActionSupport.executeReadAction$default(ReadWriteActionSupport.kt:15)
	at com.intellij.openapi.application.CoroutinesKt.constrainedReadAction(coroutines.kt:62)
	at com.intellij.openapi.application.CoroutinesKt.readAction(coroutines.kt:29)
	at com.intellij.configurationStore.ComponentStoreImplKt.getStateForComponent(ComponentStoreImpl.kt:827)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponent(ComponentStoreImpl.kt:379)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$suspendImpl(ComponentStoreImpl.kt:279)
	at com.intellij.configurationStore.ComponentStoreImpl.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreImpl.kt)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.commitComponents$intellij_platform_configurationStore_impl(ComponentStoreWithExtraComponents.kt:91)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents.saveSettingsAndCommitComponents$intellij_platform_configurationStore_impl(ComponentStoreWithExtraComponents.kt:83)
	at com.intellij.configurationStore.ComponentStoreWithExtraComponents$saveSettingsAndCommitComponents$1.invokeSuspend(ComponentStoreWithExtraComponents.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:608)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:873)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:763)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:750)
2025-01-23 12:54:18,188 [3051804] SEVERE - #c.i.u.SlowOperations - IntelliJ IDEA 2024.3  Build #IC-243.21565.193
2025-01-23 12:54:18,189 [3051805] SEVERE - #c.i.u.SlowOperations - JDK: 21.0.5; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2025-01-23 12:54:18,189 [3051805] SEVERE - #c.i.u.SlowOperations - OS: Linux
2025-01-23 12:54:18,189 [3051805] SEVERE - #c.i.u.SlowOperations - Plugin to blame: OpenShift Toolkit by Red Hat version: 1.10.2-SNAPSHOT
2025-01-23 12:54:18,189 [3051805] SEVERE - #c.i.u.SlowOperations - Last Action: Exit
```

**Comment by adietish** [comment]
> @adietish hile testing using a fresh instance ( means NO context ) and trying to connect to devsandbox, i get this error as soon i click on the login dialog: `Error: Process exited with an error: 1 (Exit value: 1) Error: unknown command "login" for "helm" Did you mean this? plugin Run 'helm --help' for usage.`

This was caused by the wrong command being used when creating the oc binary wrapper:
`ToolFactory`
```java
   public CompletableFuture<Tool<Oc>> createOc(KubernetesClient client) {
==> return new Downloadable<Oc>("helm")
       .downloadAndCreate(commandName -> new OcCli(commandName, client));
  }
```

**Comment by adietish** [comment]
@sbouchet: I dont get this, but I have a lazy loading provider instead of a instance variable that's initialized when `AccountService` is instantiated.
> ```
> java.lang.Throwable: org.jboss.tools.intellij.openshift.oauth.AccountService <clinit> requests org.jboss.tools.intellij.openshift.oauth.ui.DefaultLoginProvider instance. Class initialization must not depend on services. Consider using instance of the service on-demand instead.
> ```

**Comment by adietish** [comment]
> com.intellij.diagnostic.PluginException: Empty menu item text for DeployComponentAction@MainMenu (org.jboss.tools.intellij.openshift.actions.component.DeployComponentAction). The default action text must be specified in plugin.xml or its class constructor [Plugin: org.jboss.tools.intellij.openshift]

@sbouchet: I created #957

**Comment by adietish** [comment]
> 2025-01-23 12:54:18,187 [3051803] SEVERE - #c.i.u.SlowOperations - Non-cancelable slow operations are prohibited inside read action. See SlowOperations.assertNonCancelableSlowOperationsAreAllowed javadoc.
> java.lang.Throwable: Non-cancelable slow operations are prohibited inside read action. See SlowOperations.assertNonCancelableSlowOperationsAreAllowed javadoc.
> 	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:376)
> 	at com.intellij.util.SlowOperations.assertNonCancelableSlowOperationsAreAllowed(SlowOperations.java:128)
> 	at com.intellij.ide.passwordSafe.impl.BasePasswordSafe.set(PasswordSafeImpl.kt:107)
> 	at org.jboss.tools.intellij.openshift.oauth.model.ServersRepository.account2Node(ServersRepository.java:54)

@sbouchet: I created #958

**Comment by adietish** [comment]
@sbouchet: the only issue that is related to this PR is the [failure to log in](https://github.com/redhat-developer/intellij-openshift-connector/pull/922#issuecomment-2609535912). The other issues are not related. I fixed the complaint about the service call when instantiating `AccountService` and filed #957, #958 to tackle later.

Please re-review.

**Review by sbouchet — APPROVED** [review]
after locally try different clusters set up, all looks good.

**Comment by adietish** [comment]
/override "ci/prow/e2e-openshift" "Integration UI Test with Local Kind Cluster Context Report"

**Comment by adietish** [comment]
/override "Integration UI Tests with Local Kind Cluster Context Report" "Integration UI Tests with No Context Report"

**Comment by adietish** [comment]
/override "Integration UI Tests with Local Kind Cluster Context Report" "Integration UI Tests with No Context Report"

**Comment by adietish** [comment]
/override "Aggregated Test Report", "Integration UI Tests with Local Kind Cluster Context Report", "Integration UI Tests with No Context Report", ""
