### PR TITLE
Proxy support

### LINKED ISSUE #69: Proxy support issues
[bug]

## What versions of software are you using?
- Operating System: Windows 10 Pro
- IntelliJ version: 2018.3
- OpenShift version: Minishift 3.11.0

## What did you run exactly?
Installed plugin.

## Actual behavior
Fresh install of plugin causes significant instability and IntelliJ crashing. Openshift panel is completely empty with no buttons or capacity to interact. IntelliJ degrades within a minute or two and cannot complete basic screen draws or accept any UI interactions globally before requiring forcible kill.

After several attempts to start IntelliJ and navigate settings screens before it crashed I was able to disable this plugin. All functionality returned to normal.

## Expected behaviour
Not this...

## Any logs, error output, etc?
The most concrete issue I can find seems unrelated but may be part of the problem. Underlying fabric8 library is barfing on the proxy configuration:
```
2019-08-13 12:11:46,460 [ 219739]  ERROR - llij.ide.plugins.PluginManager - Invalid proxy server configuration 
io.fabric8.kubernetes.client.KubernetesClientException: Invalid proxy server configuration
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:159)
	at io.fabric8.kubernetes.client.BaseClient.<init>(BaseClient.java:55)
	at io.fabric8.openshift.client.DefaultOpenShiftClient.<init>(DefaultOpenShiftClient.java:222)
	at io.fabric8.openshift.client.DefaultOpenShiftClient.<init>(DefaultOpenShiftClient.java:218)
... cut many, many lines ...
Caused by: java.net.MalformedURLException: unknown protocol: <snip... this was a host name without a protocol>
	at java.net.URL.<init>(URL.java:600)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at io.fabric8.kubernetes.client.utils.HttpClientUtils.getProxyUrl(HttpClientUtils.java:207)
```

It seems there is a fundamental disconnect in handling of proxy host names. In IntelliJ you select the protocol in a separate UI control and then supply a naked hostname. Attempting to include the protocol will result in an error:
image

Then fabric8 tries to trivially consume that configuration and doesn't like the syntax without protocol which results in the crash. Perhaps the broader instability is based on that low level error? Seems unlikely but you never know.

There are also lots and lots of another error that appeared in `idea.log` after installation as well. They were not there historically, and stopped after disabling the plugin... but there is nothing in the stack trace (that I could see) that points at this plugin beside that timing:
```
java.lang.Throwable: Write-unsafe context! Model changes are allowed from write-safe contexts only. Please ensure you're using invokeLater/invokeAndWait with a correct modality state (not "any"). See TransactionGuard documentation for details.
  current modality=ModalityState.NON_MODAL
  known modalities:
    ModalityState.NON_MODAL, writingAllowed=true;
    ModalityState:{[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog0,781,447,358x125,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=IDE and Plugin Updates,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]]}, writingAllowed=false;
    ModalityState:{}, writingAllowed=true;
    ModalityState:{}, writingAllowed=true;
    ModalityState:{[com.intellij.openapi.ui.impl.DialogWrapperPeerImpl$MyDialog[dialog1,438,137,1028x713,invalid,hidden,layout=java.awt.BorderLayout,APPLICATION_MODAL,title=Settings,defaultCloseOperation=DO_NOTHING_ON_CLOSE,rootPane=,rootPaneCheckingEnabled=true]]}, writingAllowed=true;
    ModalityState:{}, writingAllowed=true
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:134)
	at com.intellij.openapi.application.TransactionGuardImpl.assertWriteActionAllowed(TransactionGuardImpl.java:232)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.lambda$closeFile$1(EditorWindow.java:279)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runChange(FileEditorManagerImpl.java:1660)
	at com.intellij.openapi.fileEditor.impl.EditorWindow.closeFile(EditorWindow.java:214)
	at com.intellij.openapi.fileEditor.impl.EditorsSplitters.closeFile(EditorsSplitters.java:517)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$closeFileImpl$3(FileEditorManagerImpl.java:637)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.runChange(FileEditorManagerImpl.java:1660)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFileImpl(FileEditorManagerImpl.java:637)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.lambda$closeFile$2(FileEditorManagerImpl.java:631)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:212)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:631)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeFile(FileEditorManagerImpl.java:625)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl.closeAllFiles(FileEditorManagerImpl.java:1917)
	at com.intellij.openapi.fileEditor.impl.FileEditorManagerImpl$3.projectClosed(FileEditorManagerImpl.java:174)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:358)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:331)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:322)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:196)
	at com.sun.proxy.$Proxy67.stateChanged(Unknown Source)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.fireStateChanged(ToolWindowManagerImpl.java:1559)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.execute(ToolWindowManagerImpl.java:587)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.execute(ToolWindowManagerImpl.java:576)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.projectClosed(ToolWindowManagerImpl.java:553)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl$2.projectClosed(ToolWindowManagerImpl.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:117)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:397)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpWaitingBuses(MessageBusImpl.java:358)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:347)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:324)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:29)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:196)
	at com.sun.proxy.$Proxy26.projectClosed(Unknown Source)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectClosed(ProjectManagerImpl.java:809)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.lambda$closeProject$15(ProjectManagerImpl.java:698)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1057)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeProject(ProjectManagerImpl.java:695)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.closeAndDisposeAllProjects(ProjectManagerImpl.java:635)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$disposeSelf$6(ApplicationImpl.java:241)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:220)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:178)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:168)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:154)
	at com.intellij.openapi.application.impl.ApplicationImpl.disposeSelf(ApplicationImpl.java:239)
	at com.intellij.openapi.application.impl.ApplicationImpl.doExit(ApplicationImpl.java:818)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:788)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:777)
	at com.intellij.openapi.application.impl.ApplicationImpl.exit(ApplicationImpl.java:773)
	at com.intellij.openapi.application.impl.ApplicationImpl.restart(ApplicationImpl.java:750)
	at com.intellij.ide.plugins.PluginManagerConfigurable.shutdownOrRestartApp(PluginManagerConfigurable.java:157)
	at com.intellij.ide.plugins.PluginManagerConfigurableNew.lambda$null$9(PluginManagerConfigurableNew.java:642)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:762)
	at java.awt.EventQueue.access$500(EventQueue.java:98)
	at java.awt.EventQueue$3.run(EventQueue.java:715)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:732)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:719)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:668)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:363)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

### LINKED ISSUE #149: The connector does not honor IntelliJ proxy settings
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 7
- IntelliJ version: 2019.3
- OpenShift version: 3.11

## What did you run exactly?

- Set IntelliJ http proxy
- Install intellij-openshift-connector 

## Actual behavior
intellij-openshift-connector is proposing to download odo but fails silently.

## Expected behavior
intellij-openshift-connector honors IntelliJ http proxy and download odo

## Any logs, error output, etc?
nope

### PR DESCRIPTION
**Pull request by jeffmaury**
- Use proxy selector when downloading odo
- Setup proxy related env variables when launching odo

Fixes #149
Fixes #69
Replaces #150
Contributions from @doublefx

Signed-off-by: Jeff MAURY <jmaury@redhat.com>

## Was the change discussed in an issue?
fixes #???

### CODE REVIEW

File: src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleAction.java [hunk 1]
```diff
@@ -24,7 +24,7 @@
   public void actionPerformed(AnActionEvent anActionEvent, TreePath path, Object selected, Odo odo) {
     ApplicationsRootNode clusterNode = (ApplicationsRootNode) selected;
```
Comment (sbouchet) [inline src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleAction.java]: please remove unused variable.

File: src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java [hunk 2]
```diff
@@ -41,11 +42,22 @@
...
     protected static final String STORAGE_PREFIX = "stor";
 
+    private TestDialog previousTestDialog;
+
     @Before
     public void init() throws Exception {
-        System.setProperty(OdoCli.ODO_DOWNLOAD_FLAG, Boolean.TRUE.toString());
-        odo = OdoCli.get();
-        client = new DefaultOpenShiftClient(new ConfigBuilder().build());
+        previousTestDialog = Messages.setTestDialog(new TestDialog() {
```
Comment (sbouchet) [inline src/it/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCliTest.java]: using lambda: 
```suggestion
        previousTestDialog = Messages.setTestDialog(message -> 0);
```

File: src/main/java/org/jboss/tools/intellij/openshift/actions/storage/CreateStorageAction.java [hunk 3]
```diff
@@ -55,7 +53,6 @@ private CreateStorageDialog showDialog() {
   }
 
   public List<Integer> loadServicePorts(Odo odo, LazyMutableTreeNode projectNode, LazyMutableTreeNode applicationNode, LazyMutableTreeNode componentNode) {
```
Comment (sbouchet) [inline src/main/java/org/jboss/tools/intellij/openshift/actions/storage/CreateStorageAction.java]: this method seems not used anymore. please remove it if so and the associated imports.

File: src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java [hunk 4]
```diff
@@ -53,18 +53,11 @@
...
+    setUserObject(odo.getMasterUrl());
     this.model = model;
   }
 
-  public OpenShiftClient getClient() {
-    return client;
-  }
-
-  private OpenShiftClient loadClient() {
-    return new DefaultOpenShiftClient(new ConfigBuilder().build());
```
Comment (sbouchet) [inline src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationsRootNode.java]: please remove associated and not used imports.

File: src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java [hunk 5]
```diff
@@ -19,15 +19,15 @@
 import java.util.function.BiConsumer;
 
 public interface Odo {
-    List<Project> getProjects(OpenShiftClient client);
```
Comment (sbouchet) [inline src/main/java/org/jboss/tools/intellij/openshift/utils/odo/Odo.java]: please remove associated import.

File: src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java [hunk 6]
```diff
@@ -352,7 +231,7 @@ public void createComponentBinary(String project, String application, String con
    * ensure that $HOME/.odo/config.yaml file exists so thar we can use service related commands.
    */
   private void ensureDefaultOdoConfigFileExists() {
-    File dir = new File(HOME_FOLDER, PLUGIN_FOLDER);
+    File dir = new File(HOME_FOLDER, Constants.PLUGIN_FOLDER);
```
Comment (sbouchet) [inline src/main/java/org/jboss/tools/intellij/openshift/utils/odo/OdoCli.java]: for readability, either use Constants.HOME_FOLDER or static import PLUGIN_FOLDER.

File: src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleAction.java [hunk 7]
```diff
@@ -22,7 +22,6 @@
 public class OpenConsoleAction extends LoggedInClusterAction {
   @Override
   public void actionPerformed(AnActionEvent anActionEvent, TreePath path, Object selected, Odo odo) {
-    ApplicationsRootNode clusterNode = (ApplicationsRootNode) selected;
```
Comment (sbouchet) [inline src/main/java/org/jboss/tools/intellij/openshift/actions/cluster/OpenConsoleAction.java]: please remove also the unused import.

**Comment by sbouchet** [comment]
reviewed but still does not have a clue why the tests are failling on CI.
