### PR TITLE
Also refresh when token is changing.

### LINKED ISSUE #102: Login to cluster fails
[kind/bug]

## What versions of software are you using?
- Operating System: Windows 10 1903
- IntelliJ version: 2019.3 EAP8
- OpenShift version: 

## What did you run exactly?
Try to login to cluster

## Actual behavior
Nothing happens

## Expected behavior
I'm logged in to the cluster

## Any logs, error output, etc?
IDEA Fatal errors shows
```
java.lang.ClassCastException: class com.intellij.openapi.actionSystem.impl.ActionMenu cannot be cast to class com.intellij.ui.treeStructure.Tree (com.intellij.openapi.actionSystem.impl.ActionMenu and com.intellij.ui.treeStructure.Tree are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @3bfdc050)
	at org.jboss.tools.intellij.openshift.actions.TreeAction.getTree(TreeAction.java:32)
	at org.jboss.tools.intellij.openshift.actions.TreeAction.update(TreeAction.java:38)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.java:177)
	at com.intellij.ide.util.gotoByName.GotoActionModel.updateActionBeforeShow(GotoActionModel.java:303)
	at com.intellij.ide.util.gotoByName.GotoActionModel$ActionWrapper.lambda$getPresentation$0(GotoActionModel.java:652)
	at com.intellij.ide.util.gotoByName.GotoActionModel.lambda$updateOnEdt$4(GotoActionModel.java:456)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:309)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:441)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:424)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:407)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:779)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:698)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:421)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

### PR DESCRIPTION
**Pull request by adietish**
Signed-off-by: Andre Dietisheim <adietish@redhat.com>

## Was the change discussed in an issue?
fixes #102 

## How to test changes?

1. ASSERT: have a cluster with a project
1. EXEC: Logout of the cluster
1. EXEC: Log in again with a new token (that you can retrieve in the web-ui)

Result:
Nothing happens, the tree is not refreshed, you still see the "Please log in to the cluster"  as a child node to the cluster node in the explorer

Expected Result:
The tree should display the project as a child node of your cluster (and replace the "Please log in to the cluster").

### CODE REVIEW

File: src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModel.java [hunk 1]
```diff
@@ -180,23 +182,47 @@ public Object getRoot() {
...
-
     @Override
-    public void onUpdate(ConfigWatcher source) {
+    public void onUpdate(ConfigWatcher source, Config config) {
         try {
-            if (ConfigHelper.isKubeConfigParsable() && hasContextChanged()) {
+            if (ConfigHelper.isKubeConfigParsable()) {
+              Context context = KubeConfigUtils.getCurrentContext(this.config);
+              Context newContext = KubeConfigUtils.getCurrentContext(config);
+              if (hasServerChanged(newContext, context)
```
Comment (jeffmaury) [inline src/main/java/org/jboss/tools/intellij/openshift/tree/application/ApplicationTreeModel.java]: Maybe worth having these 2 method calls wrapped in a 
`hasContextChanged(config)`

for improved readability ?

File: src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigWatcher.java [hunk 2]
```diff
@@ -38,7 +45,8 @@ public void run() {
                     Path path = (Path) event.context();
                     path = config.getParentFile().toPath().resolve(path);
                     if (path.equals(config.toPath())) {
-                        listener.onUpdate(this);
+                        Config config = ConfigHelper.loadKubeConfig();
```
Comment (jeffmaury) [inline src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigWatcher.java]: That causes the test to fail fo me: you may get an exception because the kube config file is not fully written and this the config watcher will not call the listener and even worse, the watcher will exit the loop

Comment (adietish) [reply src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigWatcher.java]: @jeffmaury good pointer. What's the test that's reporting this?

**Comment by adietish** [comment]
@jeffmaury addressed those 2 complaints, dare to re-review please?

File: src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigWatcher.java (hunk 2 above)
Comment (jeffmaury) [reply src/main/java/org/jboss/tools/intellij/openshift/utils/ConfigWatcher.java]: 1) Log out
2) Relaunched IJ
3) Log in
